export enum PeriodEnums {
  NONE = 'NONE',
  START_OF_ENTERING_TOPICS = 'START_OF_ENTERING_TOPICS',
  END_OF_ENTERING_TOPICS = 'END_OF_ENTERING_TOPICS',
  FIRST_TOPIC_ADVERTISMENT = 'FIRST_TOPIC_ADVERTISMENT',
  FIRST_TOPIC_ADVERTISMENT_END = 'FIRST_TOPIC_ADVERTISMENT_END',
  FIRST_ALOCATION = 'FIRST_ALOCATION',
  SECOND_TOPIC_ADVERTISMENT = 'SECOND_TOPIC_ADVERTISMENT',
  SECOND_TOPIC_ADVERTISMENT_END = 'SECOND_TOPIC_ADVERTISMENT_END',
  SECOND_ALLOCATION = 'SECOND_ALLOCATION',
  IMPLEMENTATION_OF_TOPICS = 'IMPLEMENTATION_OF_TOPICS',
  DOCUMENTUM_UPLOADE = 'DOCUMENTUM_UPLOADE',
  DIPLOMA_DEFEND = 'DIPLOMA_DEFEND',
}
